#' Create a data frame mapping local license file names to remote license URLs
#'
#' This function creates a data frame that maps local license file names to
#' their corresponding remote license URLs.
#' The local file names are generated by converting the license names to
#' lowercase, replacing spaces and hyphens with underscores, and appending the
#' `.md` extension.
#' The remote file URLs are taken directly from the input `license` vector.
#' @param license A named character vector where the names are the license names
#' and the values are the corresponding remote license URLs.
#' @return A data frame with two columns: `local_file` and `remote_file`.
#' The `local_file` column contains the generated local file names,
#' and the `remote_file` column contains the corresponding remote license URLs.
#' @export
#' @family license
license_local_remote <- function(license) {
  data.frame(
    local_file = gsub("[ -]", "_", names(license)) |>
      tolower() |>
      paste0(".md"),
    remote_file = unname(license)
  )
}
